// Re-export everything from core/prompts so existing imports keep working.
export {
  buildSystemPrompt,
  renderPromptTemplate,
  getDefaultPromptTemplate,
  buildRefinementPrompt,
  injectTitle,
  buildTestScaffoldPrompt,
  buildRequirementsFromDesignPrompt,
  buildBugfixPrompt,
  buildBugfixVerificationPrompt,
  buildClarificationUserPrompt,
  buildClarifiedRequirementsUserPrompt,
  REFINE_SYSTEM,
  TESTS_SYSTEM,
  CLARIFICATION_SYSTEM,
  VIBE_TO_SPEC_SYSTEM,
  buildVibeToSpecPrompt,
  SECTIONS,
  TEMPLATES,
  DEFAULT_ROLE,
  DEFAULT_STEERING,
  REQUIREMENTS_FROM_DESIGN_SYSTEM,
  TASK_EXECUTION_SYSTEM,
  buildTaskExecutionPrompt,
  TASK_CHECK_SYSTEM,
  buildTaskCheckPrompt,
} from './core/prompts';
export type { Stage, PromptContext, BugfixStage, RequirementsFormat } from './core/prompts';
